defmodule Arcticmc.Metadata do
  @moduledoc """
  Handles fetching and parsing metadata from nfo files.
  """

  require Logger

  def get_metadata(path) when is_binary(path) do
    path =
      cond do
        File.dir?(path) ->
          Path.join([path, "tvshow.nfo"])

        String.contains?(Path.basename(path), ".") ->
          metadata_path(path)

        true ->
          path
      end

    Logger.debug("Reading metadata from #{path}")
    File.read(path)
  end

  def get_metadata(path) do
    Logger.debug("Attempting to get metadata for an invalid path: #{inspect(path)}")
    ""
  end

  @doc """
  Gets the path to the metadata file.

  Metadata files should be stored in files which have the same root name (without extension) as the
  media that they describe. Files are stored as XML in a `.nfo` file, as generated by Kodi and TinyMediaManager.
  """
  def metadata_path(path), do: "#{Path.rootname(path)}.nfo"
end
